name: uas_mobile_2315091047
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  http: ^0.13.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/organic_waste.jpeg
    - assets/plastic_waste.jpeg
    - assets/paper_waste.jpeg
    - assets/metal_waste.jpeg
    - assets/glass_waste.jpeg
    - assets/b3_waste.jpeg
    - assets/compost_tip.png
    - assets/shopping_bag_tip.png
    - assets/digital_docs_tip.png
    - assets/water_bottle_tip.png
    - assets/upcycling_tip.png